package de.jlandsmann.discordTeamGenerator.utils;

import java.util.*;

public class NameProvider {

    private static final List<String> names = Arrays.asList(
            "Afrikanischer Elefant",
            "Afrikanischer Strauß",
            "Afrikanischer Wildhund",
            "Aldabra-Riesenschildkröte",
            "Bongo",
            "Bonobo",
            "Erdferkel",
            "Flusspferd",
            "Gepard",
            "Kaffernbüffel",
            "Katta",
            "Mandrill",
            "Netzgiraffe",
            "Nilwaran",
            "Nyala",
            "Okapi",
            "Rappenantilope",
            "Roter Vari",
            "Spießbock",
            "Springbock",
            "Steppenzebra",
            "Thomson-Gazelle",
            "Tüpfelhyäne",
            "Warzenschwein",
            "Weißschwanzgnu",
            "Westafrikanischer Löwe",
            "Westlicher Flachlandgorilla",
            "Westlicher Schimpanse",
            "Zwergflusspferd",
            "Blauer Pfau",
            "Borneo-Orang-Utan",
            "Chinesisches Schuppentier",
            "Gangesgavial",
            "Großer Panda",
            "Indischer Elefant",
            "Isabellbär",
            "Japanmakak",
            "Kleiner Panda",
            "Komodowaran",
            "Königstiger",
            "Leistenkrokodil",
            "Panzernashorn",
            "Rosaflamingo",
            "Schneeleopard",
            "Sibirischer Tiger",
            "Taiwanischer Schwarzbär",
            "Trampeltier",
            "Amerikanischer Bison",
            "Gabelbock",
            "Grizzlybär",
            "Wolf",
            "Galapagos-Riesenschildkröte",
            "Mittelamerikanischer Tapir",
            "Abgottschlange",
            "Australische Großscharbe",
            "Brasilianische Riesenvogelspinne",
            "Brasilianische Wanderspinne",
            "Brasilianischer Riesenläufer",
            "Echte Achatschnecke",
            "Gelbe Anakonda",
            "Gila-Krustenechse",
            "Goliath-Vogelspinne",
            "Goliathfrosch",
            "Goliathkäfer",
            "Grüner Inselleguan",
            "Grüner Leguan",
            "Haariger Wüstenskorpion",
            "Indischer Riesenskorpion",
            "Lehmanns Pfeilgiftfrosch",
            "Mexikanische Rotknie-Vogelspinne",
            "Puffotter",
            "Riesenbockkäfer",
            "Schrecklicher Pfeilgiftfrosch",
            "Texas-Klapperschlange",
            "Todesotter",
            "Östliche Braunschlange",
            "Königspinguin",
            "Riesenotter",
            "Kegelrobbe",
            "Glattstirnkaiman",
            "Diamantschildkröte",
            "Koala",
            "Rote Riesenkänguru",
            "Dingo",
            "Helmkasuar",
            "Blauzungenskink",
            "Jaguar",
            "Kapuzineräffchen",
            "Große Ameisenbär",
            "Rotaugenlaubfrosch",
            "Lama",
            "Dickhornschaf",
            "Eisbär",
            "Polarwolf",
            "Rentier"
    );

    public static List<String> getNames() {
        return new ArrayList<>(names);
    }

    public static String getName() {
        final var idx = (int) (Math.random() * names.size());
        return names.get(idx);
    }
}
